# Site settings
title: York Solutions
email: justincyork@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web development in Monett, Missouri.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: justincyork
github_username:  'york-solutions'

# Build settings
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM
  hard_wrap: false
  
ga:
  account: 'UA-61161051-1'
  
disqus:
  shortname: 'yorksolutions'