# Site settings
title: York Solutions, LLC
subtitle: Website Development in Monett, Missouri
email: justin@york.io
description: > # this means to ignore newlines until "baseurl:"
  Justin York is a full-stack web developer based in Monett, Missouri. He has a love for JavaScript and a unique expertise in using the FamilySearch API.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://york.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  
  - 'justincy'
  - 'york-solutions'
phone: '(417) 319-4160'

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  
ga:
  account: 'UA-61161051-1'
  
disqus:
  shortname: 'yorksolutions'