title: York Solutions, LLC

subtitle: Genealogy Web Development

email: justin@york.io

description: > # this means to ignore newlines until "baseurl:"
  Justin York is a full-stack web developer based in Monett, Missouri. He has a love for JavaScript and a unique expertise in using the FamilySearch API.
  
url: "http://york.io" # the base hostname & protocol for your site

logo: "/assets/img/logo-500.png"

github_username:  
  - 'justincy'
  - 'york-solutions'
  
phone: '(417) 319-4160'

ga:
  account: 'UA-61161051-1'
  
gems:
  - jekyll-seo-tag