# Site settings
title: York Solutions, LLC
subtitle: Website Development in Monett, Missouri
email: justincyork@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Experts in custom website development serving the Monett, Missouri area. 
  We can help with creating new websites, updating existing websites, enhancing SEO, 
  setting up blogs, and many other tasks related to managing your website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yorksolutions.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  'york-solutions'
phone: '(417) 319-4160'

markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM
  hard_wrap: false
  
ga:
  account: 'UA-61161051-1'
  
disqus:
  shortname: 'yorksolutions'